### ISSUE TITLE
개발 시, 이슈 기록에 관한 건

### ISSUE THREAD

**Issue by Altera520** [leaphigh/WWL#31]
WWL과 별도로 각자 개발 시에 만나는 이슈들을 수집하고 아카이빙을 하고 싶은데 어떻습니까?!
추후 개발할때 이슈만나면 최우선적으로 찾아볼 수 있는 저장소를 만들고 공유하면 서로간에 도움될 것 같은데..

- 검색이 편해야 한다. 깃헙 레포만으로는 힘들다. (ex. 깃북과 algolia 또는 lunr의 조합)
- 아카이브 템플릿 지정 (ex. 상황 - 발생 원인 - 해결 방식)

**Comment by sangwonCoco** [comment]
반대하지는 않으나 나는 참여하지 않겠음. 이유는 아래와 같음.

1. 관심사 측면에서 봤을 때 효용성이 없다.
배민 등의 서비스 기업에서는 이슈 해결 과정을 기록한 위키가 있는 것으로 알고 있는데 조직 단위에서는 이슈 해결 과정을 기록하는게 유의미하다 생각함.
왜냐하면 대부분의 경우 공통된 기술 스택, 개발 환경을 사용하기 때문에 관심사가 일치함.
관심사가 일치하기에 본인이 겪은 문제를 다른 팀원들이 겪을 확률이 높음.
그러나 조직 단위가 아닌 개인 단위의 차원에서는 관심사가 같지 않음. 그렇기에 효용성이 없음.


2. 기존 저장소(구글, 스택오버플로우, 깃헙 이슈) 보다 나은가?
저장소를 만들고자 하는 이유에서 "최우선적으로 찾아볼 수 있는 저장소"를 이야기 했음.
그러나 막 저장소를 만든 직후에는 저장소 자체에 정보가 별로 없음. 
또한 대부분의 문제 해결법은 넓은 범위에서 구글, 좁은 범위에서 스택오버플로우, 관련된 오픈소스의 저장소 이슈에서 찾을 수 있는데 굳이 새로운 저장소를 만든다? 난 크게 의미 없다고 생각함.
다른 사람들은 모르겠으나 나 같은 경우는 결국 최우선적으로 구글을 찾을 것임.


위 근거들을 바탕으로 굳이 별도의 시간을 써서 공통의 이슈 해결 저장소를 만들 필욘 없다고 생각함.

내 입장은 이렇고 꼭 해야 한다면 개인 매체(블로그, 유튜브)를 통해 하거나, 다른 마음 맞는 사람이랑 하는 것을 추천
