### ISSUE TITLE
Pull Request 이후 병합에 관한 건

### ISSUE THREAD

**Issue by Altera520** [leaphigh/WWL#8]
현재 개인 브랜치에서 main브랜치로 풀리퀘를 요청할 때 규칙이 정해져있지 않습니다.
원할한 피드백을 주고받기 위해 아래의 프로세스로 수행하는 것은 어떠신지 여쭤봅니다.

1. 개인 브랜치에서 main 브랜치로 PR시 리뷰어 지정
2. 지정한 리뷰어 모두로부터 approve 받은 이후에 PR 생성한 본인이 직접 merge (approve 시 간략한 코멘트)
- approve 받지 못했다면 수정 후 다시 PR 요청 (레포의 특성상 개발하는 것이 아니기에 approve 받지 못하는 경우는 극히 드물 것이라 예상)

**Comment by jaehong2** [comment]
확인했습니다!

**Comment by sangwonCoco** [comment]
예쓰!~!
